---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bggdb-pvc
  namespace: bggns
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  labels:
    app: bggdb
  namespace: bggns

spec:
  replicas: 1
  selector:
    matchLabels:
      app: bggdb
      name: bggdb-po
  template:
    metadata:
      labels:
        name: bggdb-po
        app: bggdb
      namespace: bggns
    spec:
      volumes:
        - name: bggdb-storage
          persistentVolumeClaim:
            claimName: bggdb-pvc
      containers:
        - name: bggdb
          image: chukmunnlee/bgg-database:nov-2025
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: bggdb-config
                  key: DB_USER
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bggdb-secret
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: bggdb-storage
              mountPath: /var/lib/mysql

---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
  labels:
    app: bggdb
spec:
  type: ClusterIP
  selector:
    app: bggdb
    name: bggdb-po
  ports:
    - port: 3306
