---
apiVersion: v1
kind: Namespace
metadata:
  name: myns
  labels:
    app: wen
    dept: eng

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddv-deploy
  labels:
    app: dov
  namespace: myns

spec:
  replicas: 4
  selector:
    matchLabels:
      app: dov-bear
  template:
    metadata:
      name: dov-bear
      labels:
        app: dov-bear
      namespace: myns
    spec:
      containers:
        - name: dov-bear-container
          image: chukmunnlee/dov-bear:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "5000"
            - name: INSTANCE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 5000
              protocol: TCP
